[project]
name = "plox"
authors = [{ name = "Kamil Turek", email = "kamil.turek@hotmail.com" }]
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = ["ruff", "pre-commit"]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "T201"]
